export const DUMMY_DATA = {
    커피: [
        { name: '아메리카노', 
          price: 4000, 
          soldOut: false},
        { name: '카페라떼', 
          price: 4500, 
          soldOut: true },
        { name: '프라푸치노', 
          price: 4000, 
          soldOut: false },
        { name: '돌체 라떼', 
          price: 4500, 
          soldOut: false },
        { name: '카페모카', 
          price: 4200, 
          soldOut: false },
        { name: '아이스 커피', 
          price: 3800, 
          soldOut: false },
        { name: '카푸치노', 
          price: 4200, 
          soldOut: true },
        { name: '에스프레소', 
          price: 3500, 
          soldOut: false },
        { name: '아포카토', 
          price: 5000, 
          soldOut: false },
        { name: '바닐라 라떼', 
          price: 4500, 
          soldOut: false },
      ],
      스무디: [
        { name: '딸기 스무디', 
          price: 5000, 
          soldOut: false },
        { name: '포도 스무디', 
          price: 5500, 
          soldOut: true },
        { name: '사과 스무디', 
          price: 5000, 
          soldOut: false },
        { name: '복숭아 스무디', 
          price: 5500, 
          soldOut: false },
        { name: '망고 스무디', 
          price: 5000, 
          soldOut: false },
        { name: '블루베리 스무디', 
          price: 5500, 
          soldOut: false },
        { name: '망고 자몽 스무디', 
          price: 5500, 
          soldOut: false },
        { name: '피치 오렌지 스무디', 
          price: 5000, 
          soldOut: false },
      ],
      에이드: [
        { name: '레몬 에이드', 
          price: 5000, 
          soldOut: false },
        { name: '자몽 에이드', 
          price: 5500, 
          soldOut: false },
        { name: '청포도 에이드', 
          price: 5000, 
          soldOut: false },
        { name: '파인애플 에이드', 
          price: 5500, 
          soldOut: false },
        { name: '라임 에이드', 
          price: 5000, 
          soldOut: false },
        { name: '복숭아 에이드', 
          price: 5500, 
          soldOut: false },
        { name: '블루베리 에이드', 
          price: 5500, 
          soldOut: false },
        { name: '라즈베리 에이드', 
          price: 5500, 
          soldOut: false },
        { name: '파인애플 자몽 에이드', 
          price: 5500, 
          soldOut: false },
      ],
      차: [
        { name: '홍차', 
          price: 3500, 
          soldOut: false },
        { name: '녹차', 
          price: 4000, 
          soldOut: true },
        { name: '페퍼민트 차', 
          price: 4000, 
          soldOut: false },
        { name: '캐모마일 차', 
          price: 4000, 
          soldOut: false },
        { name: '자스민 차', 
          price: 4500, 
          soldOut: false },
        { name: '레몬차', 
          price: 3800, 
          soldOut: false },
        { name: '자몽차', 
          price: 4200, 
          soldOut: false },
        { name: '파인애플차', 
          price: 4200, 
          soldOut: false },
        { name: '라벤더 차', 
          price: 4200, 
          soldOut: false },
        { name: '로즈마리 차', 
          price: 4200, 
          soldOut: false },
      ],
      주스: [
        { name: '오렌지 주스', 
          price: 4000, 
          soldOut: false },
        { name: '사과 주스', 
          price: 4000, 
          soldOut: false },
        { name: '토마토 주스', 
          price: 4200, 
          soldOut: false },
        { name: '포도 주스', 
          price: 4500, 
          soldOut: true },
        { name: '망고 주스', 
          price: 5000, 
          soldOut: false },
        { name: '자몽 주스', 
          price: 4200, 
          soldOut: false },
      ],
}