export const DUMMY_DATA = {
    커피: [
        { name: '아메리카노', price: 4000 },
        { name: '카페라떼', price: 4500 },
        { name: '아메리카노', price: 4000 },
        { name: '카페라떼', price: 4500 },
        { name: '아메리카노', price: 4000 },
        { name: '카페라떼', price: 4500 },
        { name: '아메리카노', price: 4000 },
        { name: '카페라떼', price: 4500 },
    ],
    스무디: [
        { name: '딸기 스무디', price: 5000 },
        { name: '포도 스무디', price: 5500 },
        { name: '딸기 스무디', price: 5000 },
        { name: '포도 스무디', price: 5500 },
        { name: '딸기 스무디', price: 5000 },
        { name: '포도 스무디', price: 5500 },
        { name: '딸기 스무디', price: 5000 },
        { name: '포도 스무디', price: 5500 },
        { name: '딸기 스무디', price: 5000 },
        { name: '포도 스무디', price: 5500 },
    ],
    커피2: [
        { name: '아메리카노', price: 4000 },
        { name: '카페라떼', price: 4500 },
        { name: '아메리카노', price: 4000 },
        { name: '카페라떼', price: 4500 },
        { name: '아메리카노', price: 4000 },
    ],
    스무디2: [
        { name: '딸기 스무디', price: 5000 },
        { name: '포도 스무디', price: 5500 },
        { name: '딸기 스무디', price: 5000 },
        { name: '포도 스무디', price: 5500 },
        { name: '딸기 스무디', price: 5000 },
        { name: '포도 스무디', price: 5500 },
        { name: '딸기 스무디', price: 5000 },
        { name: '포도 스무디', price: 5500 },
        { name: '딸기 스무디', price: 5000 },
        { name: '포도 스무디', price: 5500 },
    ],
    에이드: [
        { name: '에이드1', price: 5000 },
        { name: '에이드2', price: 5500 },
        { name: '에이드1', price: 5000 },
        { name: '에이드2', price: 5500 },
    ],
}